### ISSUE TITLE
Знаменитый баг с медпаунчем

### ISSUE THREAD

**Issue by cofecofe3** [FighterX/RU-TGMC#11]
![1515151](https://user-images.githubusercontent.com/44531035/60773154-da414900-a109-11e9-8024-6775e16bf473.png)

**Comment by Fray2** [comment]
Паунч на ТГ может вмещать в себя только обычный First-Aid kid, адвансед же не влезает. Фича, но лучше добавить возможность вмещать все.

**Comment by cofecofe3** [comment]
> 
> 
> Паунч на ТГ может вмещать в себя только обычный First-Aid kid, адвансед же не влезает. Фича, но лучше добавить возможность вмещать все.

У меня и обычный не вмещался. Если достаешь его - обратно уже не всунешь.

**Comment by cofecofe3** [comment]
For EN:
If you take a first-aid kit from a pounch, then you can’t return it back. In chat complaint about the size.
