### ISSUE TITLE
Башня танка

### ISSUE THREAD

**Issue by ghost** [FighterX/RU-TGMC#59]
С башней происходит какой-то баг, она сама куда-то поворачивает, к примеру когда мех.вод поворачивает танк, такое может случится.

**Comment by DeadLineSS13** [comment]
Башня хоть зафиксирована?

**Comment by ghost** [comment]
В смысле?

**Comment by DeadLineSS13** [comment]
Есть кнопка Fix/unfix tower.

**Comment by ghost** [comment]
Не помогает, нажимал на неё
Всё равно сама поворачивается

**Comment by DeadLineSS13** [comment]
Надо бы добавить строчку, которая пишет зафиксирована или нет.
